### ISSUE TITLE
Possible issue with the CMakefile.txt

### ISSUE THREAD

**Issue by Dhopal** [zoom/meetingsdk-linux-raw-recording-sample#3]
See these 2 lines- https://github.com/zoom/meetingsdk-linux-raw-recording-sample/blob/main/demo/CMakeLists.txt#L4-L5

What is the expected c++ standard here c++11, c++14?

**Comment by tanchunsiong** [comment]
it should be c++ 11, thanks for spotting this @Dhopal . I've updated the cmakelist

**Comment by Dhopal** [comment]
Hi @tanchunsiong . Thanks for the quick reply. I don't think we need both the lines. It just adds `-std=c++11` twice in the final command. Also, I'm getting the following error while running the this part `cd build && make` inside the Ubuntu-Dockerfile. 

`app/demo/meeting_sdk_demo.cpp:77:61: error: invalid new-expression of abstract class type 'ZoomSDKAudioRawData'
   77 | ZoomSDKAudioRawData* audio_source = new ZoomSDKAudioRawData();`
   
   Can you cross check if your dockerfile for ubuntu is working fine.

**Comment by tanchunsiong** [comment]
@Dhopal Ive not updated the sample yet to the latest SDk, it should be working well with 5.16.0.

If you are using the newer SDK, you might need to make sure all the methods/interfaces are implemented.

Could you try with 5.16.0 first?

**Comment by Dhopal** [comment]
Sure. Let me try. Thanks :)
